format = """
$directory
$git_branch$git_status
"""

[directory]
home_symbol = "⛺"

substitutions = [
  { from = "/\\.config(/|$)", to = "/⚙️$1", regex = true },
  { from = "/\\.local(/|$)", to = "/🐧$1", regex = true },
  { from = "/\\.cache(/|$)", to = "/♻️$1", regex = true },

  { from = "/downloads(/|$)", to = "/📬$1", regex = true },
  { from = "/documents(/|$)", to = "/🕯️$1", regex = true },
  { from = "/pictures(/|$)", to = "/📸$1", regex = true },
  { from = "/videos(/|$)", to = "/📽️$1", regex = true },
  { from = "/music(/|$)", to = "/🎷$1", regex = true },

  { from = "/projects(/|$)", to = "/🎚️$1", regex = true },
  { from = "/scores(/|$)", to = "/🎼$1", regex = true },
  { from = "/library(/|$)", to = "/☕$1", regex = true },

  { from = "/coding(/|$)", to = "/👩🏻‍💻$1", regex = true },
  { from = "/bin(/|$)", to = "/󱆃 $1", regex = true },
  { from = "/Trash(/|$)", to = "/🗑️$1", regex = true },
  { from = "/office(/|$)", to = "/💼$1", regex = true },
  { from = "/archive(/|$)", to = "/📜$1", regex = true },

  { from = "/001_Confidential(/|$)", to = "/🥷🏻$1", regex = true },
  { from = "/004_People(/|$)", to = "/👥$1", regex = true },

  { from = "/Gov(/|$)", to = "/🏛️$1", regex = true },
  { from = "/uk(/|$)", to = "/🇬🇧$1", regex = true },
  { from = "/us(/|$)", to = "/🇺🇸$1", regex = true },

  { from = "/Health(/|$)", to = "/🏥$1", regex = true },
  { from = "/Finance(/|$)", to = "/💹$1", regex = true },
  { from = "/Academic(/|$)", to = "/👩🏻‍🎓$1", regex = true },
]
