general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# After 1 hour: dim screen
listener {
    timeout = 3600
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# After 1 hour: keyboard light off
listener { 
    timeout = 3600
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0
    on-resume = brightnessctl -rd rgb:kbd_backlight
}

# After 65 minutes: lock screen
listener {
    timeout = 3900
    on-timeout = loginctl lock-session
}

# After 66 minutes: screen off
listener {
    timeout = 3960
    on-timeout = hyprctl dispatch dpms off
    on-resume  = hyprctl dispatch dpms on ; brightnessctl -r
}

# After 2 hours: suspend
listener {
    timeout = 7200
    on-timeout = systemctl suspend
}
