splash = false

#LG 34" (depending on HDMI port)
wallpaper {
	monitor = HDMI-A-1
	path = ~/Pictures/wallpapers/wallhaven-og563p_3440x1440.png
	fit_mode = cover
}

#Dell 27" (depending on HDMI port)
wallpaper {
	monitor = DP-1
	path = ~/Pictures/wallpapers/wallhaven-og563p_3440x1440.png
	fit_mode = cover
}

#Thinkpad
wallpaper {
	monitor = eDP-1
	path = ~/Pictures/wallpapers/wallhaven-og563p_3440x1440.png
	fit_mode = cover
}
