#Fonts
font_family      family='FiraCode Nerd Font' postscript_name=FiraCodeNF-Reg
font_size 	 12
bold_font        auto
italic_font      auto
bold_italic_font auto

#Scrollback
scrollback_lines 5000

#Windows
window_padding_width 8
confirm_os_window_close 0

#Keyboard
map kitty_mod+u scroll_page_up
map kitty_mod+f scroll_page_down
map kitty_mod+l next_tab
map kitty_mod+h previous_tab
map kitty_mod+t new_tab
map kitty_mod+w close_tab
map kitty_mod+0 set_background_opacity +0.1
map kitty_mod+9 set_background_opacity -0.1
map f9 launch --type=os-window --cwd=current
# Word navigation in terminal (Alt+h/l)
map alt+b send_text all \x1bb
map alt+w send_text all \x1bf
map alt+h send_text all \x1b[D
map alt+l send_text all \x1b[C

# Colors
include ~/.cache/wal/colors-kitty.conf
background_opacity 1
dynamic_background_opacity yes
